server:
  port: 8010
  servlet:
    context-path: /

#监控节点信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8080
  zipkin:  #zipkin链路地址
    base-url: http://localhost:9411/
  redis:
    database: 0
    host: 47.103.65.169
    password: tangcp
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制），默认 8
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制），默认 -1ms
        max-idle: 8 # 连接池中的最大空闲连接，默认 8
        min-idle: 0 # 连接池中的最小空闲连接，默认 0

  datasource:
    platform: mysql
    url: jdbc:mysql://47.103.65.169:3306/belazy_base?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
    dribver-class-name: com.mysql.jdbc.Driver
    max-active: 1000
#开启mybatis日志
logging:
  level:
    com.belazy.basics.auth.mapper: debug

#开启驼峰命名
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

#oauth2配置
oauth:
  authUri: http://127.0.0.1:8010/oauth/token
  grantType: password
  clientId: BelazySecretID
  clientSecret: BelazySecret